branch-defaults:
  dev:
    environment: test-dev
    group_suffix: null
  master:
    environment: jkwening-prod
    group_suffix: null
global:
  application_name: jkwening
  branch: null
  default_ec2_keyname: jkwening
  default_platform: Python 3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
